server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: smev-api-mock

logging:
  level:
    HTTP: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: ${spring.application.name}
    description: SMEV API mock
    version: 1.0.0
